apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.fullname }}-service
    labels:
      app: {{ .Values.name }} # Label for the service itself
spec:
    ports:
    - port: {{ .Values.global.service.port }}
      targetPort: 80
    selector:
      # These labels must match the labels in the prd/deployment.yaml template.spec.template.metadata.labels
      app: nginx
      env: prd