{{- $secretName := .Values.global.requiredSecretName -}}
{{- $namespace := .Values.global.namespace -}}
{{- $secret := lookup "v1" "Secret" $namespace $secretName }}
{{- if not $secret -}}
  {{- required (printf "The required Secret '%s' in namespace '%s' was not found. Please create it or comment out this check." $secretName $namespace) "" -}}
{{- end -}}

apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.fullname }}-service
    labels:
      app: {{ .Values.name }} # Label for the service itself
spec:
    ports:
    - port: {{ .Values.global.service.port }}
      targetPort: 80
    selector:
      # These labels must match the labels in the prd/deployment.yaml template.spec.template.metadata.labels
      app: nginx
      env: prd